apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: q9szn4sit-dotnet-basic
  janus-idp.io/tekton: q9szn4sit-dotnet-basic
  backstage.io/kubernetes-id: q9szn4sit-dotnet-basic
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: q9szn4sit-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
